### ISSUE TITLE
Game gives no feedback for non-forced movement into a Spring

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#2] opened 2019-11-19 22:35 UTC
Attempting to move into a Spring doesn't seem to work, but the game doesn't print out any message informing you of that.

Forced movement works.

**Comment by kikigame** [comment] 2019-11-20 13:27
Springboards are a kind of trap, and you can't move onto a trap without the "force" action (that's what "force" does). So in that sense, it's not a bug.

But it agree that there should be a message, probably not a y/n prompt, to indicate why you can't move.

**Comment by kikigame** [comment] 2019-11-23 22:00
Implemented & on github; will be in the next binary build for the backend.

**Closed as completed by kikigame** 2019-11-23 22:00 UTC
Labels: enhancement
